"""add page to chat_sessions

Revision ID: f08402136acc
Revises: 56802690e5df
Create Date: 2026-08-20 15:48:24.939812
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f08402136acc'
down_revision: Union[str, None] = '56802690e5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('page', sa.String(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_page'), 'chat_sessions', ['page'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_page'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'page')
    # ### end Alembic commands ###
